version: '3'
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "4000:3000"
    volumes:
      - ./certs:/app/certs:ro
    env_file:
      - .env
