version: '3'
services:
  node_app:
    image: dangtinh1221/be-emodesk:latest
    container_name: be-emodesk
    working_dir: /app
    ports:
      - "4000:3000"
    volumes:
      - ./certs:/app/certs:ro
    env_file:
      - .env
